#!/bin/bash
########################################################################################
#                                                                                      #
#                              fires controller script                                 #
#                                                                                      #
########################################################################################

path_to_fires='/home/path/to/fires-master/scripts'     # e.g. /usr/bin/fires-master/scripts
path_to_click='/home/path/to_click'                    # e.g. /usr/bin/Click_X86_64
path_to_dssp='/home/path/to_dssp'                      # e.g. /usr/bin

########################################################################################

pdb_target=$1
chain=$2
pdbid=`echo $pdb_target | awk -F'.' '{print $1}'`
current=`pwd`
dd=$(date '+%d-%b-%Y-%H-%M-%S')
rr=$RANDOM
wk=$dd"-"$rr"-"$pdb_target

1>&2 echo "FiRES: Find Repeated Elements in Structure"
1>&2 echo "Usage: ./fires <pdb file> <chain name>";
1>&2 echo "FiRES  is going to be running at : "$wk

mkdir "$wk"
cd "$wk"
cp "$current"/"$pdb_target" .
perl "$path_to_fires"/fires_v0.pl -pdb "$pdb_target" -c "$chain" -path $path_to_fires -pclick $path_to_click -pdssp $path_to_dssp
cp "$pdbid"* "$current"
cd "$current"
1>&2 echo "Removing folder : "$wk"
rm -r "$wk"
